### ISSUE TITLE
Unused code in NPC_Villager and MON_Beast

### ISSUE THREAD

**Issue by schwi1996** [COMP2522/project-ruby#128]
https://github.com/COMP2522/project-ruby/blob/df1e14aa67d46da063471ae1c04e7bda18fe63d8/src/main/java/org/project/NPC_Villager.java#L33-L34

https://github.com/COMP2522/project-ruby/blob/df1e14aa67d46da063471ae1c04e7bda18fe63d8/src/main/java/org/project/MON_Beast.java#L33-L34

I tried commenting out these two lines of code and the game works without an issue.

**Comment by amritjhatu** [comment]
This issue has been resolved. Thank you for your suggestion, Helen.
