### ISSUE TITLE
Create a collision/bounds class to handle all collisions

### ISSUE THREAD

**Issue by pbucci** [COMP2522/project-ruby#141]
https://github.com/COMP2522/project-ruby/blob/df1e14aa67d46da063471ae1c04e7bda18fe63d8/src/main/java/org/project/Element.java#L20

a quick find/replace search lets me know that you have many classes that have collision as a state variable, it would make sense to take these out of the class states and instead create a Boundary object that each class that needs to collide owns.

![image](https://user-images.githubusercontent.com/3506567/228304007-05877ff9-031c-4bac-8a38-7f97bf5b9386.png)

**Comment by abhishekchouhannk** [comment]
We utilized a Rectangle object to handle bounds!!!
