### ISSUE TITLE
AC-144_Some Repeated code in ElementHandler

### ISSUE THREAD

**Issue by breader1** [COMP2522/project-ruby#144]
https://github.com/COMP2522/project-ruby/blob/df1e14aa67d46da063471ae1c04e7bda18fe63d8/src/main/java/org/project/ElementHandler.java#L29

```
  public void setElement() {
    gp.elements[0] = new Ruby();
    gp.elements[0].setWorldX(9 * GamePanel.TILE_SIZE);
    gp.elements[0].setWorldY(7 * GamePanel.TILE_SIZE);

    gp.elements[1] = new Ruby();
    gp.elements[1].setWorldX(11 * GamePanel.TILE_SIZE);
    gp.elements[1].setWorldY(7 * GamePanel.TILE_SIZE);

    gp.elements[2] = new Door();
    gp.elements[2].setWorldX(10 * GamePanel.TILE_SIZE);
    gp.elements[2].setWorldY(11 * GamePanel.TILE_SIZE);

    gp.elements[3] = new Fire();
    gp.elements[3].setWorldX(10 * GamePanel.TILE_SIZE);
    gp.elements[3].setWorldY(31 * GamePanel.TILE_SIZE);

    gp.elements[4] = new PowerUp();
    gp.elements[4].setWorldX(10 * GamePanel.TILE_SIZE);
    gp.elements[4].setWorldY(14 * GamePanel.TILE_SIZE);
  }
```

This is a similar issue as the previous repeated code. Can probably init these things with a for loop depending on what element they are.

**Comment by abhishekchouhannk** [comment]
Going to work on this issue, thanks for pointing it out.

I'm thinking of making a spawn system, maybe that will work

**Comment by abhishekchouhannk** [comment]
Didn't remove original code, because it's just initial setup, but added a spawn system that spawns rubies and flames to random locations !! Thanks for the idea
