### ISSUE TITLE
Repeated code in these two methods

### ISSUE THREAD

**Issue by breader1** [COMP2522/project-ruby#146]
https://github.com/COMP2522/project-ruby/blob/df1e14aa67d46da063471ae1c04e7bda18fe63d8/src/main/java/org/project/ElementHandler.java#L54

https://github.com/COMP2522/project-ruby/blob/df1e14aa67d46da063471ae1c04e7bda18fe63d8/src/main/java/org/project/ElementHandler.java#L64

It may be easier to init this in one for loop.

**Comment by amritjhatu** [comment]
I just feel it is easier to follow along with separation should someone work on my code. My personal preference is to keep them separated.
